ReachFive/identity-web-ui-sdk

- package-lock.json
- package.json
I've upgraded the `core-js` dependency version.
> Upgrade the 'core-js' dependency version

- CHANGELOG.md
- package-lock.json
- package.json
- Update the changelog.
- Upgrade the version to `1.0.0-alpha.2`.
> Release v1.0.0 alpha.2

- .circleci/config.yml
- README.md
- src/client.js
I've implemented the CI of the UI SDK on CircleCi (like the other SDKs).
I've created two jobs:
- `test` which is run at each branch push.
- `release` which is run when a new tag is pushed on the `master` branch.
> Implement CI 

- mocks/svg.js
- package-lock.json
- package.json
- rollup.config.js
- src/components/form/fields/passwordField.jsx
- src/components/form/fields/simplePasswordField.jsx
- src/components/form/socialButtonsComponent.jsx
- src/widgets/auth/authWidget.js
- tests/widgets/auth/__snapshots__/authWidget.test.js.snap
- tests/widgets/passwordReset/__snapshots__/passwordResetWidget.test.js.snap
Social providers' icons are not displayed as React elements like the other icons. Thus I am using two rollup plugins to import SVG in the bundle`@svgr/rollup` and `rollup-plugin-url`.
I've also corrected a bug with the display of the eye icon in the signup form.
> Fix the svg icons display

- CHANGELOG.md
- package-lock.json
- package.json
- Update the changelog.
- Bum the version to `1.0.0-alpha.3`.
> Release v1.0.0-alpha.3

- .gitignore
- package.json
- rollup.config.js
I've updated the path of the bundles to be ISO with the Core SDK.
> Change the paths of the bundles

- README.md
- package-lock.json
- package.json
- src/client.js
- src/widgets/auth/views/forgotPasswordViewComponent.jsx
- src/widgets/auth/views/signupViewComponent.jsx
https://app.asana.com/0/1108828962586858/1157855289922453/f
> Add the `returnTo` parameter for password reset et signup

- .circleci/config.yml
- RELEASE.md
- package-lock.json
- package.json
- Write a `RELEASE.md` guide.
- Revert the commit to test the CircleCi "deploy" job.
> Write a release guide & revert the test commit to fix the "deploy" job

- .gitignore
- package-lock.json
- package.json
No Asana ticket associated with this PR.
> Small technical improvements about dependencies and gitignore

- src/widgets/auth/views/loginViewComponent.jsx
- tests/widgets/auth/__snapshots__/authWidget.test.js.snap
Last PR for the [Asana ticket about remember me](https://app.asana.com/0/980131104682803/1156801986427609/f)
> Move persistent in auth object

- index.d.ts
- src/client.js
- src/components/form/cardComponent.jsx
- src/main.js
- src/widgets/socialAccounts/socialAccountsWidget.jsx
- src/widgets/webAuthn/webAuthnDevicesWidget.js
- tests/widgets/socialAccounts/__snapshots__/socialAccountsWidget.test.js.snap
**Asana task**: https://app.asana.com/0/1111569008372652/1181397055064775
> Implement a widget to manage fido2 devices

- src/widgets/webAuthn/webAuthnDevicesWidget.js
**Asana task**: https://app.asana.com/0/1111569008372652/1182786040452489
> Handle better error when device is already registered

- src/components/form/formComponent.jsx
**Asana ticket**: https://app.asana.com/0/1141396442496489/1172559372679836
> Display overloaded error message if there are

- src/components/form/formFieldFactory.js
[Asana](https://app.asana.com/0/980131104682803/1131655632042821/f)
> Add custom fields types (email & phone)

- src/components/form/fields/consentField.jsx
- src/components/form/formFieldFactory.js
Asana ticket
[[Core] Account opt-out consents prevail over payload opt-out consents during /signup call](https://app.asana.com/0/1142049698926411/1190049921355514/f)
> Send consent type according to their real value

- src/widgets/passwordReset/passwordResetWidget.jsx
[Conflits entre templates de Password reset et de Account suspension](https://app.asana.com/0/1108828962586858/1189455447833603/f)
> Ajout d'un paramètre purpose lors du reset password.

- src/components/form/fieldCreator.jsx
- src/components/form/fields/passwordField.jsx
- src/components/form/formComponent.jsx
- src/widgets/auth/views/signupViewComponent.jsx
- [Asana](https://app.asana.com/0/1142049698926411/1163374331637446)
- [Asana](https://app.asana.com/0/1142049698926411/1164120760438069)
* Add a debounce for focused input validation
* Notify when password contains words contained in given name, family name, or email
> Basic form validation changes

- src/components/form/fields/passwordField.jsx
- src/widgets/auth/views/signupViewComponent.jsx
Instead of strict string matching, use blacklisted words as additional input for zxcvbn.
> Use zxcvbn in form validation

- src/components/form/fields/passwordField.jsx
- src/components/form/fields/passwordPolicyRules.jsx
**Asana ticket**: https://app.asana.com/0/1141396442496489/1163374331637444
> Add a check rule for password strength

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/form/fields/passwordField.jsx
- src/components/form/passwordPolicyComponent.jsx
Revert the new check rule for password strength since the wordings are not yet deployed.
> Release v1.11.1

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/form/fields/passwordField.jsx
- src/components/form/fields/passwordPolicyRules.jsx
I've cherry picked in this branch the commit `c0d4456f99527ad671dec8cf2330b8438c8cb211` that I've reverted 4 days ago (release too soon).
> Release v1.11.2

- package-lock.json
- package.json
[[SDK UI] Girondins Bordeaux: Bug Authentification](https://app.asana.com/0/869408964704224/1198981500150917/f)
> Revert SDK Core v1.17.2

- src/components/form/socialButtonsComponent.jsx
- src/providers/apple/apple.js
**Asana ticket**: https://app.asana.com/0/1141396442496489/1199242103944589
**Result**
> Change the style of the Apple button

- .circleci/config.yml
- CHANGELOG.md
- README.md
- RELEASE.md
- package-lock.json
- package.json
also some formatting stuff, similar to recent changes in sdk-core
> Release v1.15.0

- src/components/form/fields/consentField.jsx
- tests/widgets/auth/__snapshots__/authWidget.test.js.snap
- tests/widgets/auth/authWidget.test.js
**Asana ticket**: https://app.asana.com/0/1141396442496489/1199633287992181
> Allow to make a consent mandatory

- src/components/form/fields/consentField.jsx
- src/components/form/formFieldFactory.js
- src/components/form/passwordSignupFormComponent.jsx
- src/widgets/profileEditor/profileEditorWidget.jsx
- tests/widgets/auth/authWidget.test.js
**Asana ticket**: https://app.asana.com/0/1141396442496489/1200481278330380
> Handle archived consents

- src/components/form/passwordSignupFormComponent.jsx
- src/components/reCaptcha.js
- src/widgets/auth/views/forgotPasswordViewComponent.jsx
- src/widgets/auth/views/loginViewComponent.jsx
- src/widgets/auth/views/loginWithPasswordViewComponent.jsx
- src/widgets/passwordless/passwordlessWidget.jsx
[CA-1067](https://reach5.atlassian.net/browse/CA-1067)
> Add Captcha generation token for signup, forgot password, loginWithPassword

- CHANGELOG.md
- src/components/form/formFieldFactory.js
[Jira](https://reach5.atlassian.net/browse/CA-1584)
Consider consent version's language in signup payload
[PR ciam-app](https://github.com/ReachFive/ciam-app/pull/3043)
> [CA-1584] Consider consent version's language in signup payload

- index.d.ts
- src/client.js
- src/main.js
- src/widgets/mfa/MfaCredentialsWidget.jsx
[CA-1932](https://reach5.atlassian.net/browse/CA-1932)
> [CA-1932] Add email mfa registration + verification

- src/widgets/mfa/MfaCredentialsWidget.jsx
- tests/widgets/mfa/MfaCredentialsWidget.test.js
- tests/widgets/mfa/__snapshots__/MfaCredentialsWidget.test.js.snap
https://reach5.atlassian.net/browse/CA-1988
> [CA-1988] Add second factor removal

- package-lock.json
- package.json
- src/widgets/auth/authWidget.js
- src/widgets/auth/views/loginViewComponent.jsx
- src/widgets/auth/views/loginWithPasswordViewComponent.jsx
- src/widgets/stepUp/mfaStepUpWidget.jsx
[Jira ticket](https://reach5.atlassian.net/browse/CA-2143)
> [CA-2143] Initiate step up during login with password when required

- src/helpers/errors.js
- src/widgets/mfa/MfaCredentialsWidget.jsx
- src/widgets/mfa/mfaListWidget.jsx
[JIRA](https://reach5.atlassian.net/browse/CA-2430)
> [CA-2430] Display user error message in MFA widgets instead of "Unexpected error"

- src/widgets/emailEditor/emailEditorWidget.jsx
[Audit de sécurité Google reCaptcha : Renforcer la sécurité autour de l'usage de la fonction update email](https://reach5.atlassian.net/browse/CA-2902)
> [CA-2902] Captcha pour Update Email

- package-lock.json
- package.json
- rollup.config.js
- src/components/form/fields/birthdayField.jsx
[CA-3024](https://reach5.atlassian.net/browse/CA-3024)
[CA-3024]: https://reach5.atlassian.net/browse/CA-3024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CA-3024] Validation on birthdate month and day compatibility + add age restriction message

- src/components/form/socialButtonsComponent.jsx
Related to https://github.com/ReachFive/ciam-app/pull/3881
> [CA-2960] Parse provider with variant format

- .eslintrc.json
- package-lock.json
- package.json
- src/components/form/cardComponent.jsx
- src/components/form/fieldCreator.jsx
- src/components/form/fields/identifierField.jsx
- src/components/form/fields/passwordField.jsx
- src/components/form/fields/passwordPolicyRules.jsx
- src/components/form/fields/phoneNumberField.jsx
- src/components/form/fields/simplePasswordField.jsx
- src/components/form/formControlsComponent.jsx
- src/components/form/socialButtonsComponent.jsx
- src/components/reCaptcha.js
- src/components/widget/widget.jsx
- src/components/widget/widgetContainerComponent.jsx
- src/core/authResult.js
- src/core/identityEventManager.js
- src/core/theme.js
- src/core/validation.js
- src/helpers/base64.js
- src/helpers/transformObjectProperties.js
- src/helpers/utils.js
- src/widgets/auth/views/loginViewComponent.jsx
- src/widgets/mfa/MfaCredentialsWidget.jsx
- src/widgets/passwordless/passwordlessWidget.jsx
- src/widgets/phoneNumberEditor/phoneNumberEditorWidget.jsx
- src/widgets/stepUp/mfaStepUpWidget.jsx
Enable ESLint with plugins for React, TypeScript and browser compatibility checks.
> Configure ESLint

- CHANGELOG.md
- package-lock.json
- package.json
- Add Ping provider
- Fix dateField validation import
- Fix identifierField error when initilized with an empty value
> Release v1.21.0

- package-lock.json
- package.json
- src/widgets/stepUp/mfaStepUpWidget.jsx
[JIRA](https://reach5.atlassian.net/browse/CA-3221)
> [CA-3221] Supprimer le paramètre AT lors de l'appel à la méthode verifyMfaPasswordless du sdk core au niveau des widgets concernés

- index.d.ts
- src/components/form/formControlsComponent.jsx
- src/widgets/mfa/MfaCredentialsWidget.jsx
- src/widgets/stepUp/mfaStepUpWidget.jsx
- tests/widgets/mfa/MfaCredentialsWidget.test.js
- tests/widgets/mfa/__snapshots__/MfaCredentialsWidget.test.js.snap
https://reach5.atlassian.net/browse/CA-3119
> [CA-3119] improvement UX mfa credential registering + step up

- index.d.ts
- src/widgets/socialAccounts/socialAccountsWidget.jsx
[JIRA](https://reach5.atlassian.net/browse/CA-3245)
> [CA-3245] Fonction showSocialAccounts permettant l'ajout de variants d'un connecteur Line

- CHANGELOG.md
- package-lock.json
- package.json
- Handle provider variants correctly in showSocialAccount.
> Release v1.23.1

- index.d.ts
- package-lock.json
- package.json
https://reach5.atlassian.net/browse/CA-3237
> [CA-3237] Add new variable locale

- src/widgets/socialAccounts/socialAccountsWidget.tsx
- tests/widgets/socialAccounts/__snapshots__/socialAccountsWidget.test.js.snap
- tests/widgets/socialAccounts/socialAccountsWidget.test.js
[CA-3446](https://reach5.atlassian.net/browse/CA-3446)
[CA-3446]: https://reach5.atlassian.net/browse/CA-3446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CA-3446] Unlink : gérer l'erreur du token pas assez frais

- CHANGELOG.md
- package-lock.json
- package.json
- TypeScript migration
- Fix dateField validation when value is empty
- Show API error when trying to unlink a social account with a non-fresh access_token
> Release v1.25.0

- package-lock.json
- package.json
- src/components/widget/widget.tsx
- src/core/theme.ts
- src/types/styled.d.ts
- tests/theme.test.ts
- tests/widgets/socialLogin/__snapshots__/socialLogin.test.ts.snap
- tests/widgets/socialLogin/socialLogin.test.ts
- types/identity-ui.d.ts
J'en ai aussi profiter pour améliorer et ajouter quelques tests sur la gestion du theming.
> [CA-3525] fix themes config forwarding in createWidget function

- CHANGELOG.md
- package-lock.json
- package.json
- types/identity-ui.d.ts
- Make `@rollup/rollup-linux-x64-gnu` dependency optional
- Fix React hook warning due to mismatch of React versions
- Resolve not wrapped in act warning issue in tests
- Fix custom theme option forwarding
- Prevent phone-number field validation on empty value
> Release v1.25.3

- CHANGELOG.md
- package-lock.json
- package.json
- MFA factor selection does not appear when multiple factors are activated.
- Phone number field on reset password view should handle `withCountrySelect` options.
> Release v1.30.1

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/form/fields/simpleField.d.ts
- types/identity-ui.d.ts
- Country selector on PhoneNumber field was displayed with wrong size.
> Release v1.30.2

- src/widgets/mfa/MfaCredentialsWidget.tsx
- tests/widgets/mfa/MfaCredentialsWidget.test.js
- tests/widgets/mfa/__snapshots__/MfaCredentialsWidget.test.js.snap
- types/identity-ui.d.ts
[CA-4465](https://reach5.atlassian.net/browse/CA-4465)
[CA-4465]: https://reach5.atlassian.net/browse/CA-4465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CA-4465] Add phone number input should only be displayed if no value is already defined

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/widget/widget.tsx
- tests/widgets/auth/__snapshots__/authWidget.test.js.snap
- tests/widgets/mfa/__snapshots__/MfaCredentialsWidget.test.js.snap
- tests/widgets/mfa/__snapshots__/mfaListWidget.test.js.snap
- tests/widgets/passwordReset/__snapshots__/passwordResetWidget.test.js.snap
- tests/widgets/passwordless/__snapshots__/passwordlessWidget.test.js.snap
- tests/widgets/profileEditor/__snapshots__/profileEditorWidget.test.js.snap
- tests/widgets/socialAccounts/__snapshots__/socialAccountsWidget.test.js.snap
- tests/widgets/socialLogin/__snapshots__/socialLogin.test.ts.snap
- types/identity-ui.d.ts
- Fix phone number country select styles
> Release v1.31.1

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/form/formComponent.jsx
- types/identity-ui.d.ts
> Release v1.31.2

- rollup.config.js
- src/components/form/fields/phoneNumberField.tsx
https://reach5.atlassian.net/browse/CA-4542
> [CA-4542] Value the phone number to null when not specified

- package-lock.json
- package.json
- rollup.config.js
- src/components/miscComponent.tsx
https://npmtrends.com/marked-vs-remarkable
| Module | Size |
| ------------- | ------------- |
| Remarkable | 173.86KB (4.60%) |
| Marked | 95.95KB (2.59%) |
> Replace remarkable with marked

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/form/fields/birthdayField.tsx
- src/components/form/fields/dateField.tsx
- tests/components/form/fields/birthdateField.test.tsx
- types/identity-ui.d.ts
- Fix birthday field value format
> Release v1.32.1

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/form/fields/birthdayField.tsx
- src/components/form/fields/dateField.tsx
- tests/components/form/fields/dateField.test.tsx
> Release v1.32.2

- CHANGELOG.md
- src/components/form/fieldCreator.tsx
- src/components/form/fields/phoneNumberField.tsx
- tests/components/form/fields/phoneNumberField.test.tsx
- types/identity-ui.d.ts
Fix phoneNumberField so phone number is not in the payload instead of always valuating it to null
> [CA-4547] Fix phoneNumberField

- src/providers/kakaotalk/kakaotalk.ts
Problème rapporté par Rimowa.
https://developers.kakao.com/docs/latest/en/kakaologin/design-guide#color
> Fix Kakao brand color

- src/components/form/fields/phoneNumberField.tsx
- src/widgets/mfa/trustedDevicesWidget.tsx
[CA-4692](https://reach5.atlassian.net/browse/CA-4692)
[CA-4692]: https://reach5.atlassian.net/browse/CA-4692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CA-4692] Phone number field validation should not triggered on initialization

- CHANGELOG.md
- package-lock.json
- package.json
- types/identity-ui.d.ts
- Allow to define onSuccess and onError callback on all widgets.
- Allow to list and remove trusted devices.
- Add a button in MfaList widget to delete credential.
- Fix phoneNumberField so phone number is not in the payload instead of always valuating it to null.
- Use the right color for Kakao provider as defined in the design guidelines.
> Realease v1.33.0

- src/components/widget/widget.tsx
- src/components/widget/widgetContainerComponent.tsx
- tailwind.config.cjs
- tests/widgets/auth/__snapshots__/authWidget.test.ts.snap
- tests/widgets/emailEditor/__snapshots__/emailEditorWidget.test.ts.snap
- tests/widgets/mfa/__snapshots__/MfaCredentialsWidget.test.ts.snap
- tests/widgets/mfa/__snapshots__/mfaListWidget.test.ts.snap
- tests/widgets/passwordEditor/__snapshots__/passwordEditorWidget.test.ts.snap
- tests/widgets/passwordReset/__snapshots__/passwordResetWidget.test.ts.snap
- tests/widgets/passwordless/__snapshots__/passwordlessWidget.test.ts.snap
- tests/widgets/phoneNumberEditor/__snapshots__/phoneNumberEditorWidget.test.ts.snap
- tests/widgets/profileEditor/__snapshots__/profileEditorWidget.test.ts.snap
- tests/widgets/socialAccounts/__snapshots__/socialAccountsWidget.test.ts.snap
- tests/widgets/socialLogin/__snapshots__/socialLogin.test.ts.snap
[CA-4720](https://reach5.atlassian.net/browse/CA-4720)
[CA-4720]: https://reach5.atlassian.net/browse/CA-4720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CA-4720] Limits Tailwind styles to our widgets scope

- CHANGELOG.md
- package-lock.json
- package.json
- types/identity-ui.d.ts
- Limits Tailwind styles to widgets scope.
> Release v1.33.1

- CHANGELOG.md
- package-lock.json
- package.json
- types/identity-ui.d.ts
- ProfileEditor should update consents with key in snake_case
> Release v1.33.2

- CHANGELOG.md
- package-lock.json
- package.json
before bump version waiting for sdk core to be released
> Release v1.37.0
