ReachFive/identity-web-ui-sdk

.circleci/config.yml, .editorconfig
The `release` job (that I have renamed `deploy`) was triggered at each push on the `master` branch. I've fixed it such that the only trigger is the push of a new tag.
=> Fix the deploy job

src/widgets/passwordReset/passwordResetWidget.jsx
The `canShowPassword` password property can be enabled on the password reset widget.
=> Enable the 'canShowPassword' property on the password reset widget

.circleci/config.yml, package-lock.json, package.json
I've temporarily added the `-dry--run` option (https://docs.npmjs.com/cli/publish) to test the Circle ci `deploy` job.
=> Test the CircleCi 'deploy' job

.circleci/config.yml
The `deploy` job is not triggered when a new tag is pushed on the `master` branch.
According to this [discussion](https://discuss.circleci.com/t/build-workflow-not-triggered-when-tag-is-pushed/19577/4), the `test` job needed filters as well.
=> Fix the 'deploy' job

src/components/form/fieldCreator.jsx
Validation should not be applied to empty and non-required fields.
=> Fix form validation

src/widgets/passwordReset/passwordResetWidget.jsx
Reverts ReachFive/identity-web-ui-sdk#56
The proposed solution adds a new mandatory parameter which breaks compatibility.
=> Revert "Ajout d'un paramètre purpose lors du reset password."

.circleci/config.yml
**Asana ticket**: https://app.asana.com/0/1141396442496489/1180780219291915
The token used to authenticate to the npm repository was invalid (probably because it was generated by Egor who has no longer access to our project). So I've created a CircleCi context to group all the env variables required by both Web SDKs.
This PR changes the CircleCi configuration to use the NPM_TOKEN variable in the `reachfive` context.
=> Use the env variables in the CircleCi "reachfive" context

src/widgets/auth/views/signupWithWebAuthnViewComponent.jsx
**Asana ticket**: https://app.asana.com/0/1141396442496489/1199350022369287
=> Webauthn signup doesn't take into account  the `return_to_after_email_confirmation` param

src/components/form/buttonComponent.jsx, src/components/form/webAuthAndPasswordButtonsComponent.jsx, tests/widgets/auth/__snapshots__/authWidget.test.js.snap
The "password" and "webauthn" buttons cannot have the same `data-test-id` for the tests.
=> Distinguish the data-test-id on the webauthn/password buttons

CHANGELOG.md, package-lock.json, package.json
Bumps core-sdk to [1.20.1](https://github.com/ReachFive/identity-web-core-sdk/releases/tag/v1.20.1)
=> Release v1.12.0

src/helpers/utils.js, src/widgets/auth/views/loginViewComponent.jsx
Validation is still the same, it will be addressed in another ticket/PR. The main issue is that once an entry is recognized as a phone number, only numbers can be entered in the field. Thus, entering an email starting with numbers is impossible. If the identifier field is not recognized as either a phone number or an email, it's still possible to submit the form.
=> Add dedicated field for custom identifier in `LoginView`

index.d.ts, src/client.js, src/main.js
Parce que j'en ai marre d'avoir à manipuler des types `any` et de ne pas voir les options possibles quand on utilise le SDK UI dans un projet en TypeScript (comme la sandbox par exemple).
J'ai repris les description de [la doc en ligne](https://developer.reachfive.com/sdk-ui/index.html).
Autre amélioration, j'ai exporté une référence au SDK Core initialisé et utilise par le SDK UI.
Ça permet de ne mas avoir à instancie une deuxième instance du SDK Core si on a besoin d'appeler directement ses méthodes, mais surtout d'avoir accès à l'event manager du SDK Core pour pouvoir utiliser son api.
Par exemple pour écouter l'event `authenticated` lorsque l'on utilise un composant UI comme `Auth` ou `SocialLogin`  : 
```typescript
client.core.on("authenticated", onAuthenticated);
```
Si on utilisait …
=> Better types exposing

constants.ts, index.d.ts
```'const' initializer in an ambient context must be a string or numeric literal]```
=> migrate constants to a regular TS file. (should be defined in related components in a future TS rewriting)
`AuthOptions` not found.
=> fix import types

src/components/form/fields/dateField.jsx
[CA-3450](https://reach5.atlassian.net/browse/CA-3450)
[CA-3450]: https://reach5.atlassian.net/browse/CA-3450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CA-3450] La composition d'un custom_field de type date est toujours vérifié, même s'il est facultatif

.circleci/config.yml, package-lock.json, package.json
`@rollup/rollup-linux-x64-gnu` is required to build on CircleCI but it's actually installed with NPM in the CircleCI's workflow and then added to the bundle dependencies published on NPM.
That is wrong because it become required on every project using our SDK UI...
=> @rollup/rollup-linux-x64-gnu dependency should be optional

package-lock.json, package.json
Resolves this kind of warning message in tests execution : 
```
console.error
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```
=> Fix: styled-component's react hook warning due to react version

tests/widgets/socialAccounts/socialAccountsWidget.test.js
Fix this kind of warning :
```
console.error
Warning: An update to withIdentities(Component) inside a test was not wrapped in act(...).
When testing, code that causes React state updates should be wrapped into act(...):
act(() => {
/* fire events that update state */
});
/* assert on the output */
```
=> Fix: not wrapped in act warning issue in tests

package-lock.json, package.json, src/client.tsx
Dans une PR précédente je suis repassé de React v18 à React v16 pour résoudre un problème de compatibilité avec d'autres dépendances, mais j'ai omis de repasser la syntaxe d'utilisation de react-dom à ce qu'elle était avant React v18.
=> Use the right syntax according to react-dom version

CHANGELOG.md, package-lock.json, package.json
Due to the de-synchronized release v1.25.4 : https://github.com/ReachFive/identity-web-ui-sdk/pull/190/commits
We backport changelog and package.json version in this PR.
=> Changelog v1.25.4

package-lock.json, package.json, src/widgets/stepUp/mfaStepUpWidget.tsx, tests/widgets/mfa/mfaStepUpWidget.test.js, types/identity-ui.d.ts
[CA-3587](https://reach5.atlassian.net/browse/CA-3587)
La gestion de l'option `showStepUpStart` qui permet de choisir entre afficher un bouton pour exécuter la requête requestStepUp manuellement ou de l'exécuter à l'affichage n'était pas bien géré et résultat d'une page blanch à l'affichage.
[CA-3587]: https://reach5.atlassian.net/browse/CA-3587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CA-3587] MFA stepUp main view initialization and rendering conditions

src/client.tsx
Les messages d'erreurs utilisateurs qui doivent être affiché à la place du composant si il y a un problème sont mal capté et ne s'affichent donc pas.
=> fix error message handling

src/components/form/fields/phoneNumberField.tsx, tests/widgets/mfa/__snapshots__/MfaCredentialsWidget.test.js.snap
[CA-4020](https://reach5.atlassian.net/browse/CA-4020)
In this PR:
- phone number field now sends null instead of an empty string when the widget is empty at loading
[CA-4020]: https://reach5.atlassian.net/browse/CA-4020?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CA-4020] Transform empty string to null value for sending.

CHANGELOG.md, package-lock.json, package.json
- Add a `allowAuthentMailPhone` boolean option to hide email and password field (keep only custom identifier) on login widget
- Add a possibility to display a country selector on phone number fields
- Add Okta provider
- Add visual marker to labels for required fields
- Add possibility to define custom labels for social buttons
- [showSocialAccounts] Link : afficher le bon variant et non celui par défaut
=> Release v1.28.0

src/widgets/stepUp/mfaStepUpWidget.tsx
[CA-4396](https://reach5.atlassian.net/browse/CA-4396)
The view to display factor options when multiple identifiers are activeted in MFA was not displayed.
[CA-4396]: https://reach5.atlassian.net/browse/CA-4396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CA-4396] MFA factor selection does not appear when multiple factors are activated

src/components/form/fields/phoneNumberField.tsx, src/types/css-modules.d.ts, tests/widgets/mfa/__snapshots__/MfaCredentialsWidget.test.js.snap, tests/widgets/passwordless/__snapshots__/passwordlessWidget.test.js.snap, types/identity-ui.d.ts
[CA-4412](https://reach5.atlassian.net/browse/CA-4412)
Il s'avère que le problème vient d'un problème dans l'injection des styles de base prédéfini par la lib react-phone-number-input.
Sur Safari, la variable CSS manquante rend le style calculé invalide là où sur Chrome elle semble juste être ignorée.
[CA-4412]: https://reach5.atlassian.net/browse/CA-4412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CA-4412] Le sélecteur de country dans de champ PhoneNumber n'apparait pas à la bonne taille sur Safari desktop et iOS

CHANGELOG.md, package-lock.json, package.json, src/components/form/fields/dateField.tsx, src/components/form/fields/phoneNumberField.tsx, src/components/miscComponent.tsx, tests/widgets/mfa/__snapshots__/MfaCredentialsWidget.test.js.snap, tests/widgets/passwordless/__snapshots__/passwordlessWidget.test.js.snap, types/identity-ui.d.ts
- Allow to trust a device during step up when RBA is enabled and the new box is checked
- Replace remarkable with marked
- Replace luxon with date-fns [^3]
- Removed zxcvbn dependency and use new `getPasswordStrength` SDK Core's method instead.
- Dedupe React dependencies
- Display asterix on phone number field's label when required
- Set a min width on date field's day and year select
[^3]: Don't import locale files anymore and use builtin [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) to translate dates thanks to `intlFormat` method (https://date-fns.org/v4.1.0/docs/intlFormat). 
| Avant | Après | Evolution (%) |
| :----: | :-----: | :------------: |
| 3.69MB | 2.24MB | -39.2954% |
=> Release v1.32.0

package-lock.json, package.json, rollup.config.js, tests/widgets/auth/__snapshots__/authWidget.test.js.snap, tests/widgets/mfa/__snapshots__/MfaCredentialsWidget.test.js.snap, tests/widgets/mfa/__snapshots__/mfaListWidget.test.js.snap, tests/widgets/passwordReset/__snapshots__/passwordResetWidget.test.ts.snap, tests/widgets/passwordless/__snapshots__/passwordlessWidget.test.js.snap, tests/widgets/profileEditor/__snapshots__/profileEditorWidget.test.js.snap, tests/widgets/socialLogin/__snapshots__/socialLogin.test.ts.snap, types/identity-ui.d.ts
During the release au React v18 upgrade, there is an issue with update of `styled-components` and his method `createGlobalStyle` used to inject global styles.
In ou use case it is used to inject <PhoneNumberInput/> component styles.
With the option `withCountrySelect` enabled to display the country flags selector, the flag was not styled.
I managed to fix this issue. It was due to a rollup option to defined the browser context.
=> Upgrade styled-components to v5.3.11

src/components/form/fields/consentField.tsx, src/main.ts, src/widgets/profileEditor/profileEditorWidget.tsx, tests/widgets/profileEditor/profileEditorWidget.test.ts
[CA-4747](https://reach5.atlassian.net/browse/CA-4747)
L'idéal serait que la clé d'un consentement soit en valeur d'une propriété "key" et non une clé de la structure Map utilisée.
Le mieux serait même que `consents` soit un array et non un map.
Mais bon, difficile de changer ça maintenant sans créer un breaking change pour les utilisateurs de l'api ou du sdk core...
[CA-4747]: https://reach5.atlassian.net/browse/CA-4747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CA-4747] Profile editor should update consents with key in snakecase

.editorconfig, CHANGELOG.md, package-lock.json, package.json, rollup.config.js, src/components/ui/alert-dialog.tsx, src/components/widget/widget.tsx, src/widgets/mfa/mfaListWidget.tsx, tailwind.config.cjs, tests/widgets/mfa/__snapshots__/MfaCredentialsWidget.test.ts.snap, tests/widgets/mfa/__snapshots__/mfaListWidget.test.ts.snap, tsconfig.json, types/identity-ui.d.ts
- Allow to trust device during mfa credential registration
- Embed TailwindCSS utils in bundle
- Wrap dialog with theme provider (react portal)
`Error: Can't resolve @/lib/utils` lors de l'importation du SDK dans un projet.
`@/lib/utils` contient des fonctions utilitaires pour Tailwind.
@sachaMemmir5 avait défini ce fichier dans le build Rollup comme "external", c'est à dire qu'il ne doit pas être embarqué dans le bundle généré mais de fait doit être importé de manière global par l'intégrateur. D'où l'erreur ci-dessus car l'intégrateur ne peux pas le savoir.
Le but de cette manœuvre était de régler un problème d'application des styles quand Sacha a testé ans Storybook l'intégration de Tailwind/Shadcn dans le SDK UI.
Après analyse je constate que ce problème venait non pas de `@/lib/utils` …
=> Release v1.34.0

CHANGELOG.md, package-lock.json, package.json, src/widgets/auth/views/forgotPasswordViewComponent.tsx, tests/widgets/auth/authWidget.test.ts, types/identity-ui.d.ts
[CA-4936](https://reach5.atlassian.net/browse/CA-4936)
- Reset password with phone number should send phone number value in payload
La problème bien de la transimision  du phoneNumber entre la vue `ForgotPasswordPhoneNumberView` et `ForgotPasswordCodeView` lié à la mauvaise utilisation d'une valeur de state React dans callback `onSuccess`. Le state n'étant pas encore mis à jour dans le workflow de React (appel de `setPhoneNumber` dans la méthode `callback`) lors de l'appel à `onSuccess`.
Désolé,  pas mal de code formatting automatique lié à une petite reconfiguration de mes settings sur VSCode.
[CA-4936]: https://reach5.atlassian.net/browse/CA-4936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Release v1.34.1

eslint.config.mjs, package-lock.json, package.json, src/components/form/passwordSignupFormComponent.tsx, src/helpers/utils.ts, src/widgets/auth/views/forgotPasswordViewComponent.tsx, src/widgets/auth/views/signupWithWebAuthnViewComponent.tsx, types/identity-ui.d.ts
[CA-4940](https://reach5.atlassian.net/browse/CA-4940)
Depends on https://github.com/ReachFive/identity-web-core-sdk/pull/272 and https://github.com/ReachFive/ciam-app/pull/5597
[CA-4940]: https://reach5.atlassian.net/browse/CA-4940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CA-4940] Pouvoir tracer l'origine lors d'une demande de réinitialisation de mot de passe
